#pragma once

namespace Input { 
	struct GameControls { 
		struct XboxController { 
		enum XButtons { 
			DPAD_UP = XINPUT_GAMEPAD_DPAD_UP,
			DPAD_DOWN = XINPUT_GAMEPAD_DPAD_DOWN,
			DPAD_LEFT = XINPUT_GAMEPAD_DPAD_LEFT,
			DPAD_RIGHT = XINPUT_GAMEPAD_DPAD_RIGHT,
			START = XINPUT_GAMEPAD_START,
			BACK = XINPUT_GAMEPAD_BACK,
			LEFT_THUMB = XINPUT_GAMEPAD_LEFT_THUMB,
			RIGHT_THUMB = XINPUT_GAMEPAD_RIGHT_THUMB,
			LEFT_SHOULDER = XINPUT_GAMEPAD_LEFT_SHOULDER,
			RIGHT_SHOULDER  = XINPUT_GAMEPAD_RIGHT_SHOULDER,
			A_BUTTON = XINPUT_GAMEPAD_A,
			B_BUTTON = XINPUT_GAMEPAD_B,
			X_BUTTON = XINPUT_GAMEPAD_X,
			Y_BUTTON = XINPUT_GAMEPAD_Y
		};}; // XboXController

		struct Controls { 
		enum Buttons { 
			KEY_NULL	= 0x0,
			KEY_UP		= 0x1,
			KEY_DOWN	= (KEY_UP * 2),
			KEY_LEFT	= (KEY_DOWN * 2),
			KEY_RIGHT	= (KEY_LEFT * 2),
			KEY_START	= (KEY_RIGHT * 2),
			KEY_PAUSE = KEY_START,
			KEY_SELECT	= (KEY_PAUSE * 2),
			KEY_INTERACT= (KEY_SELECT * 2),
			KEY_RUN		= (KEY_INTERACT * 2),
			KEY_CANCEL	= (KEY_RUN * 2)
		};}; // Buttons
	};
}

/* eof */