#pragma once

namespace Input { 
	struct GameControls { 
		enum XButtons { 
			DPAD_UP = XINPUT_GAMEPAD_DPAD_UP,
			DPAD_DOWN = XINPUT_GAMEPAD_DPAD_DOWN,
			DPAD_LEFT = XINPUT_GAMEPAD_DPAD_LEFT,
			DPAD_RIGHT = XINPUT_GAMEPAD_DPAD_RIGHT,
			START = XINPUT_GAMEPAD_START,
			BACK = XINPUT_GAMEPAD_BACK,
			LEFT_THUMB = XINPUT_GAMEPAD_LEFT_THUMB,
			RIGHT_THUMB = XINPUT_GAMEPAD_RIGHT_THUMB,
			LEFT_SHOULDER = XINPUT_GAMEPAD_LEFT_SHOULDER,
			RIGHT_SHOULDER  = XINPUT_GAMEPAD_RIGHT_SHOULDER,
			A_BUTTON = XINPUT_GAMEPAD_A,
			B_BUTTON = XINPUT_GAMEPAD_B,
			X_BUTTON = XINPUT_GAMEPAD_X,
			Y_BUTTON = XINPUT_GAMEPAD_Y
		};
		enum Buttons { 
			KEY_UP,
			KEY_DOWN,
			KEY_LEFT,
			KEY_RIGHT,
			KEY_START,
			KEY_PAUSE = KEY_START,
			KEY_BACK,
			KEY_SELECT = KEY_BACK,
			KEY_INTERACT,
			KEY_RUN,
			KEY_CANCEL
		}; // Buttons
	};
}